format = """
[](bg:#F19F77 fg:#F19F77)\
$directory\
[](fg:#F19F77 bg:#E6C791)\
$git_branch\
$git_status\
[](fg:#E6C791 bg:#A5D28B)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#A5D28B bg:#85C1DD)\
$docker_context\
[](fg:#85C1DD bg:#85C1DD)\
$battery\
[](fg:#85C1DD bg:#BABCEF)\
$cmd_duration\
[](fg:#BABCEF bg:#BABCEF)\
$time\
[ ](fg:#BABCEF)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[directory]
style = "bold bg:#F19F77 fg:#1a1a1a"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bold bg:#A5D28B"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bold bg:#A5D28B"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bold bg:#85C1DD fg:#1a1a1a"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bold bg:#A5D28B"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bold bg:#A5D28B"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bold bg:#E6C791 fg:#1a1a1a"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bold bg:#E6C791 fg:#1a1a1a"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bold bg:#A5D28B"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bold bg:#A5D28B"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bold bg:#A5D28B"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bold bg:#A5D28B"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bold bg:#A5D28B"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bold bg:#A5D28B"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bold bg:#A5D28B"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bold bg:#A5D28B"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bold bg:#A5D28B"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%I:%M %p" # Hour:Minute Format
style = "bold bg:#BABCEF fg:#1a1a1a"
format = '[ ♥ $time ]($style)'

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
format = "[ $symbol$percentage ]($style)"

[[battery.display]]
threshold = 20
style = "bold bg:#85C1DD fg:#C23C73"

[[battery.display]]
threshold = 35
style = "bold bg:#85C1DD fg:#FE6A2F"

# Only show battery if less than 50%
[[battery.display]]
threshold = 100
style = "bold bg:#85C1DD fg:#1a1a1a"

[cmd_duration]
min_time = 500
show_milliseconds = false
disabled = false
style = "bold bg:#BABCEF fg:#1a1a1a"
format = '[ 󰔛 $duration]($style)'
